yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path("", include("posts.urls")),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, db_index=True, verbose_name="URL")
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст нового поста',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        verbose_name='Текст нового поста',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="comments")
    author = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="comments")
    text = models.TextField()
    created = models.DateTimeField("date published", auto_now_add=True)

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from yatube.settings import PST_ON_PAGE
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, PST_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, PST_ON_PAGE)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    title = f'Записи сообщества <{group}>'
    context = {
        'group': group,
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    post_count = post_list.count()
    paginator = Paginator(post_list, PST_ON_PAGE)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    context = {
        'post_count': post_count,
        'paginator': paginator,
        'author': author,
        'page_obj': page_obj, }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_count = Post.objects.count()
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post_count': post_count,
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_edit(request, post_id, is_edit=True):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {'form': form, 'is_edit': is_edit, 'post': post}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Новая запись{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">   
            {% if is_edit %}    
              Редактировать запись    
            {% else %} 
              Добавить запись
            {% endif %}       
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data" {% if is_edit %} action="{% url 'posts:post_edit' post.id %}" {% else %} action="{% url 'posts:post_create' %}  "{% endif %}>
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                  {{ field }}
                </label>
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    <input type="submit" value="Сохранить">
                  {% else %}
                    <input type="submit" value="Добавить">
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>  
      </div>
    </div>
  </div>           
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block content %}  
  <div class="container py-5">
  <h1>{% block header %}{{ group }}{% endblock %}</h1>
    <p>
        {{ group.description }}
    </p>
    {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a> 
        <hr>
    {% endfor %}
  </div> 
{% include '../includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}
  Последние обновления на сайте    
{% endblock %}
{% block content %}  
  <div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username%}">Все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
      </li>
    </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
  <p>{{ post.text }}</p> 
  {% if post.group %}    
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
  {% endif %}
  <br>
  <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a> 
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  </div>
{% include '../includes/paginator.html' %}
{% endblock %}
{% load cache %}
{% cache 20 index_page %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
<title>{% block title%} Пост {{ post.text|truncatechars:30}}{% endblock %}</title>
{% load thumbnail %}
{% load user_filters %}
{% block content%}
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
          {% if post.group.slug %}
            <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы</a>
            </li>
          {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора: <span>{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              Пользователь: {{ post.author }}
              <a href="{% url 'posts:profile' post.author %}">Все записи пользователя</a>
            </li>
        </ul>
      </aside>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <article class="col-12 col-md-9">
        <p>
            {{ post.text}}
        </p>
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %} 
        <a class="btn btn-primary" href="edit/">
              редактировать запись
        </a>
      </article>
    </div>
{% endblock %}

            

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
<title> {% block title%}Профайл пользователя {{ author.get_full_name }}{% endblock %} </title>
{% block content %}
<main>
      <div class="container py-5">
        <h1>Все посты пользователя {{ author}}</h1>
        <h3>Всего постов: {{ post_count }}</h3>
        <article>
            {% for post in page_obj %}
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author.username%}">Все посты пользователя</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d M Y" }}
                </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p> 
            <a class="btn btn-sm text-muted" href="{% url 'posts:post_edit' post.id %}" role="button">
Редактировать</a>
            <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
            <br>
            {% if post.group %}  
            <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}
            </article>
            {% include '../includes/paginator.html' %}
      </div>
</main>
{% endblock %}